# about render device setting.
[device]
# type : bool
# whether force not to use deferred cmdlist or not.
single-thread = false

# about render adapter setting
[device.adapter]
# type : bool
# if false, let render system automatically choose one.
# if true, set the field "index-designation" below
#   to the adapter index that you want to use.
manual-setting = false
# type : uint
# all adapter and its index information will be listed up
#   at "AutoCreated_AdapterInfoInSystem.txt" in current folder
#   after calling render system initialize function one time.
index-designation = 0
