# set using which pipeline as default.
[pipeline]
# type : bool
# if false, use complex lighting pipeline.
# if true, use simple lighting pipeline,
#   only unblured ssao active.
simply-lit = false
# type : string, valid value : ["blinn_phong", "brdf_disney"]
# the lighting model going to use in opacity deferred rendering,
#   if the name doesn't exist in valid value list it will be brdf_disney.
light-model = "brdf_disney"

# about screen space ambient occlusion.
[ssao]
# type : float
# length of the vector for nearest point calculating.
radius = 0.5
# type : float
# the range about effective occlusion.
range-start = 0.2
# type : float
# the range about effective occlusion.
range-end = 1.0
# type : float
# the min value for valid delta depth.
epsilon = 0.05
# type : uint
# gauss bluring count.
blur-count = 4

# about basic sampler setting for albedo texture etc.
[sampler]
# type : uint, valid range : [0, 3]
# 0 : D3D11_FILTER_MIN_MAG_MIP_POINT
# 1 : D3D11_FILTER_MIN_MAG_MIP_LINEAR
# 2 : D3D11_FILTER_ANISOTROPIC_8X
# 3 : D3D11_FILTER_ANISOTROPIC_16X
filter-level = 3

# about particle effect setting.
[particle]
# type : bool
# whether disable particle effect or not.
# particle processing is quite heavy but
#   play an important role in game vision.
disable-particle = false

# about bloom effect setting.
[bloom]
# type : bool
# whether disable bloom effect or not,
#   if deferred lighting model is blinn_phong it will
#   be forced to true.
disable-bloom = false
# type : float
# the threshold luminous to calculate bloom.
min-luminous = 2.0
# type : uint, valid range : [2, 8]
# affect downsampling and mips level count.
downsampling-count = 7
# type : uint
# gauss bluring count for each level's downsampling,
#   final bluring count would be
#   "downsampling-count" * "downsampling-blur-count".
downsampling-blur-count = 2
# type : uint
# gauss bluring kernel's size,
#   with radius as ((int)"gauss-kernel-size" / 2).
gauss-kernel-size = 5
# type : float, valid range : [0.0, +inf)
# gauss bluring's sigma, each weight goes
#   more average when this value gets bigger.
gauss-sigma = 1.0
# type : float
# this factor affects on final bloom intensity.
intensity-factor = 1.5
# type : float, valid range : [0.0, 1.0]
# this factor affects on attenuation about each point light.
light-source-factor = 0.02

# about dynamic exposure setting.
[exposure]
# type : bool
# whether disable dynamic exposure effect or not,
#   if true exposure will always be "static-exposure".
disable-dynamic = false
# type : float, valid range : [0.0, +inf)
# if dynamic is disabled, then exposure will always be this value,
#   else if will be used to initialize exposure buffer's first element,
#   but since loading scene doesn't have any light so it cannot affect anything.
static-exposure = 0.2
# type : float, valid range : [0.0 , 1.0]
# the speed of exposure transform,
#   as lerp(old, new, "trans-speed").
trans-speed = 0.05
# type : float, valid range : [0.0 , +inf)
# the range of dynamic exposure,
#   as clamp(expo, "min-value", "max-value").
min-value = 0.01
max-value = 10.0
# type : float, valid range : (0.0, +inf)
# the factor to decide curve of adapted luminance to exposure,
#   scene goes brighter when this value get samller,
#   as (1 / "inverse-factor" / lumin).
inverse-factor = 25.0

# about anti-aliasing fxaa setting.
[fxaa]
# type : bool
# whether disable fxaa effect or not.
disable-fxaa = false
# type : float, valid range : [0, +inf)
# the final threshold of contrast will be
#   (max("min-threshold", maxLumin * "threshold")).
threshold = 0.125
# type : float, valid range : [0, +inf)
# the minimum constract that need to be processed.
min-threshold = 0.0625
# type : int, valid range : [0, 37]
# the loop step count to found border of current pixel if it need aa,
#   if set this value to 0 fxaa will be disabled,
#   if set this value over 15 will disable [unroll] property in compute shader.
# less than 37 because of cs_5_0 model's groupshared limit is 32768 bytes.
search-step = 10
# type : int, valid range : [0, "search-step"]
# if fail to find border, this value will be setted as a virtual border.
edge-guess = 8
