# about the first scene when framework start,
#   after loading scene.
[entry-scene]
# type : string
# the name of the first scene,
#   should be same with the name
#   definites in scene file below.
name = "logo-scene"
# type : string
# the name of the first scene file,
#   the scene name definites in this file
#   should be same with the name above.
file = "logo-scene.json"
