# about the first scene when framework start,
#   after loading scene.
[entry-scene]
# [string]
# the name of the first scene,
#   should be same with the name
#   definites in scene file below.
name = "sample1-scene"
# [string]
# the name of the first scene file,
#   the scene name definites in this file
#   should be same with the name above.
file = "sample1-scene.json"
